Trello/config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :cards

  root 'main#index'
end

Trello/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Trello/app/models/card.rb
class Card < ApplicationRecord
  validates :title, presence: true,
            length: { minimum: 1 }
end

Trello/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Trello/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = Card.new
  end

  def edit
    @card = Card.find(params[:id])
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card
    else
      render 'new'
    end
  end

  def update
    @card = Card.find(params[:id])

    if @card.update(card_params)
      redirect_to @card
    else
      render 'edit'
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    redirect_to cards_path
  end

  private
    def card_params
      params.require(:card).permit(:title, :text)
    end

end

Trello/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

Trello/app/helpers/application_helper.rb
module ApplicationHelper
end

Trello/app/helpers/cards_helper.rb
module CardsHelper
end

Trello/app/helpers/main_helper.rb
module MainHelper
end

Trello/app/views/cards/_form.html.erb
<%= form_for :card, url: cards_path do |f| %>

  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

Trello/app/views/cards/edit.html.erb
<h1>Edit Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

Trello/app/views/cards/index.html.erb
<h2>These are your cards</h2>

<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Sortable - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#sortable" ).sortable();
    $( "#sortable" ).disableSelection();
  } );



  </script>

<a class="button index_button" href="/cards/new">New Card</a>
<a class="button index_button" href="/main/index">Main Page</a>
<br /><br />

<div id="sortable" class = "ui-widget-content ui-draggable ui-draggable-handle">
  <% @cards.each do |card| %>

    <div class="index_cards">
      <div class="row">
        <div class="col-lg-12 title">
          <%= card.title %>
        </div>
          <div class="row">
            <div class="col-lg-12 text">
              <%= card.text %>
            </div>
          </div>
      </div>

      <p class="card_options">
        <%= link_to 'Show More', card_path(card) %>
      </p>
      <p class="card_options">
        <%= link_to 'Edit', edit_card_path(card) %>
      </p>
      <p class="card_options">
        <%= link_to 'Destroy', card_path(card),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
      </p>
    </div>

  <% end %>

</div>


<p id="order">
  This is the order
</p>

<script>
var sortedIDs = $( ".selector" ).sortable( "toArray" );

document.write(sortedIDs)
document.getElementById('order').innerHTML = sortedIDs
</script>

sortedIDs

Trello/app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

Trello/app/views/cards/show.html.erb
<!-- <p>
  <strong>Title:</strong>
  <%= @card.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @card.text %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %>
<%= link_to 'Back', cards_path %> -->


<div class="row">
  <div class="col-sm-9">
    Card <%= @card.id %>
    <div class="row">
      <div class="col-xs-8 col-sm-6">
        <%= @card.title %>
      </div>
      <div class="col-xs-4 col-sm-6">
        <%= @card.text %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_card_path(@card) %>
<%= link_to 'Back', cards_path %>

Trello/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trello</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Trello/app/views/main/index.html.erb
<h1 class="home_title">This is the Main Page</h1>
<a class="home_link button" href="/cards">My Cards</a>